// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6KmtdusZJTU10txPmYAKxRBibSG3DAlQ',
    appId: '1:486657291251:android:59b63469594750de0c9886',
    messagingSenderId: '486657291251',
    projectId: 'ulimo-30934',
    databaseURL: 'https://ulimo-30934-default-rtdb.firebaseio.com',
    storageBucket: 'ulimo-30934.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgaK5q0Mvwt8P3_u_v_QuYbc0j6VGvusQ',
    appId: '1:486657291251:ios:6d54a876d226b1d40c9886',
    messagingSenderId: '486657291251',
    projectId: 'ulimo-30934',
    databaseURL: 'https://ulimo-30934-default-rtdb.firebaseio.com',
    storageBucket: 'ulimo-30934.appspot.com',
    iosClientId: '486657291251-22o50pb7q5l3pg4aop5i0slmuiu6n32v.apps.googleusercontent.com',
    iosBundleId: 'com.ulimo.inc',
  );
}
